-- Generated by scripts/gen-seed.ts. Do not edit by hand.

insert into public.cars (id, make, model, gen, year, country, cc, tier, hp, nm, acc, top, kg, value, blurb, pools, tastes) values
  ('ferrari-f40', 'Ferrari', 'F40', '', 1987, 'Italy', 'IT', 'Legendary', 478, 577, 4.2, 324, 1100, 412000, 'Built for Ferrari’s 40th anniversary and the last car Enzo Ferrari signed off personally. Twin-turbo V8, no power steering, no ABS.', array['apex']::text[], array['supercars']::text[]),
  ('mclaren-f1', 'McLaren', 'F1', '', 1992, 'United Kingdom', 'GB', 'Legendary', 627, 651, 3.2, 386, 1138, 980000, 'Central driving seat flanked by two passengers. Held the production car top-speed record for over a decade.', array['apex']::text[], array['supercars']::text[]),
  ('porsche-911-rs27', 'Porsche', '911 Carrera RS 2.7', 'F-series', 1973, 'Germany', 'DE', 'Legendary', 210, 255, 5.8, 245, 975, 268000, 'A homologation special with thinner steel, lighter glass and the ducktail spoiler that became a 911 signature.', array['heritage']::text[], array['classics']::text[]),
  ('toyota-2000gt', 'Toyota', '2000GT', 'MF10', 1967, 'Japan', 'JP', 'Legendary', 150, 175, 8.6, 220, 1120, 305000, 'Japan’s first serious grand tourer. Around 350 were built, with a Yamaha-developed straight-six.', array['heritage']::text[], array['classics', 'jdm']::text[]),
  ('mercedes-300sl', 'Mercedes-Benz', '300 SL Gullwing', 'W198', 1954, 'Germany', 'DE', 'Legendary', 215, 275, 8.8, 260, 1295, 498000, 'Direct fuel injection and a spaceframe chassis so tall at the sills that the doors had to open upward.', array['heritage']::text[], array['classics']::text[]),
  ('porsche-959', 'Porsche', '959', '', 1986, 'Germany', 'DE', 'Legendary', 450, 500, 3.7, 317, 1450, 512000, 'Group B technology for the road: sequential twin turbos, adjustable ride height and computer-controlled all-wheel drive.', array['apex']::text[], array['supercars']::text[]),
  ('nissan-skyline-r34', 'Nissan', 'Skyline GT-R V-Spec', 'R34', 1999, 'Japan', 'JP', 'Epic', 280, 392, 4.9, 250, 1560, 142000, 'RB26 twin-turbo straight-six and ATTESA all-wheel drive. Officially rated at 280 hp under Japan’s gentlemen’s agreement.', array['apex']::text[], array['jdm']::text[]),
  ('honda-nsx-na1', 'Honda', 'NSX', 'NA1', 1990, 'Japan', 'JP', 'Epic', 274, 285, 5.7, 270, 1365, 96000, 'An aluminium monocoque mid-engine car tuned with input from Formula 1 drivers, proving a supercar could be used daily.', array['apex']::text[], array['jdm', 'supercars']::text[]),
  ('lamborghini-countach', 'Lamborghini', 'Countach LP400', '', 1974, 'Italy', 'IT', 'Epic', 375, 368, 5.6, 290, 1065, 188000, 'Scissor doors and a wedge profile by Marcello Gandini. The early LP400 is the cleanest form, before the wings arrived.', array['heritage', 'apex']::text[], array['supercars', 'classics']::text[]),
  ('toyota-supra-a80', 'Toyota', 'Supra RZ', 'A80', 1993, 'Japan', 'JP', 'Epic', 330, 431, 4.6, 250, 1490, 88000, 'The 2JZ-GTE engine is known for handling far more boost than it left the factory with.', array['apex']::text[], array['jdm']::text[]),
  ('lancia-delta-evo', 'Lancia', 'Delta HF Integrale Evo', '', 1991, 'Italy', 'IT', 'Epic', 210, 300, 5.7, 220, 1340, 109000, 'Six consecutive World Rally Championship titles for Lancia. The Evo added wider arches and an adjustable rear spoiler.', array['apex']::text[], array['rally']::text[]),
  ('mercedes-c111', 'Mercedes-Benz', 'C111-II', '', 1970, 'Germany', 'DE', 'Epic', 350, 392, 4.8, 300, 1240, 160000, 'A four-rotor Wankel test bed in a glassfibre wedge. Mercedes famously refused the blank cheques offered to build it.', array['heritage']::text[], array['concepts']::text[]),
  ('lancia-stratos', 'Lancia', 'Stratos HF Stradale', '', 1973, 'Italy', 'IT', 'Epic', 190, 226, 6.8, 230, 980, 205000, 'Built around a Ferrari Dino V6 purely to win rallies. It took three straight World Rally Championship titles.', array['heritage']::text[], array['rally', 'classics']::text[]),
  ('jaguar-etype-s1', 'Jaguar', 'E-Type 3.8', 'Series 1', 1961, 'United Kingdom', 'GB', 'Epic', 265, 353, 7, 241, 1234, 175000, 'Launched at the 1961 Geneva show with a claimed 150 mph, disc brakes all round and a price far below its rivals.', array['heritage']::text[], array['classics']::text[]),
  ('bmw-30-csl', 'BMW', '3.0 CSL', 'E9', 1972, 'Germany', 'DE', 'Rare', 200, 277, 7.3, 220, 1165, 68000, 'A lightweight homologation coupé with aluminium panels. Its racing aero kit earned it the nickname Batmobile.', array['heritage']::text[], array['classics']::text[]),
  ('mazda-rx7-fd', 'Mazda', 'RX-7', 'FD', 1992, 'Japan', 'JP', 'Rare', 255, 294, 5.3, 250, 1250, 54000, 'A sequential twin-turbo rotary in a low, light body. Near 50:50 weight distribution.', array['street', 'apex']::text[], array['jdm']::text[]),
  ('bmw-m3-e30', 'BMW', 'M3', 'E30', 1986, 'Germany', 'DE', 'Rare', 195, 230, 6.7, 235, 1200, 71000, 'Developed to go touring-car racing, and went on to become one of the most successful touring cars ever.', array['street', 'apex']::text[], array['everyday']::text[]),
  ('alfa-giulia-gta', 'Alfa Romeo', 'Giulia Sprint GTA', 'Tipo 105', 1965, 'Italy', 'IT', 'Rare', 115, 142, 9.5, 185, 745, 62000, 'GTA stands for Gran Turismo Alleggerita: aluminium body panels over a lightened Giulia coupé.', array['heritage']::text[], array['classics']::text[]),
  ('datsun-240z', 'Datsun', '240Z', 'S30', 1969, 'Japan', 'JP', 'Rare', 151, 198, 8, 200, 1044, 44500, 'A straight-six sports car priced against British roadsters. It became the best-selling sports car of its decade.', array['heritage']::text[], array['classics', 'jdm']::text[]),
  ('ford-sierra-cosworth', 'Ford', 'Sierra RS Cosworth', '', 1986, 'United Kingdom', 'GB', 'Rare', 204, 276, 6.2, 241, 1220, 41000, 'A Cosworth-developed turbo four and a whale-tail wing, built so Ford could go Group A touring-car racing.', array['street']::text[], array['everyday', 'rally']::text[]),
  ('ford-escort-cosworth', 'Ford', 'Escort RS Cosworth', 'Mk5', 1992, 'United Kingdom', 'GB', 'Rare', 227, 304, 6.2, 232, 1275, 52000, 'Sierra Cosworth running gear under an Escort body, with a rear wing that made real downforce at road speeds.', array['street']::text[], array['rally']::text[]),
  ('lancia-stratos-zero', 'Lancia', 'Stratos HF Zero', '', 1970, 'Italy', 'IT', 'Rare', 115, 140, 9, 200, 800, 58000, 'A Bertone show car only 84 cm tall, entered through the hinged windscreen. It led directly to the rally Stratos.', array['heritage']::text[], array['concepts']::text[]),
  ('vw-golf-gti-mk1', 'Volkswagen', 'Golf GTI', 'Mk1', 1976, 'Germany', 'DE', 'Common', 110, 140, 9, 182, 810, 14000, 'Fuel injection in a small hatchback. The car that started the hot-hatch category.', array['street', 'heritage']::text[], array['everyday']::text[]),
  ('peugeot-205-gti', 'Peugeot', '205 GTI 1.9', '', 1986, 'France', 'FR', 'Common', 130, 161, 7.8, 206, 875, 12500, 'Light, short and lively at the limit. The 1.9 added torque to the 1.6’s balance.', array['street']::text[], array['everyday']::text[]),
  ('mini-cooper-s', 'Mini', 'Cooper S', 'Mk1', 1964, 'United Kingdom', 'GB', 'Common', 76, 108, 10.9, 160, 650, 9800, 'Front-wheel drive with a transverse engine. Won the Monte Carlo Rally outright in 1964.', array['street', 'heritage']::text[], array['everyday', 'rally', 'classics']::text[]),
  ('renault-clio-williams', 'Renault', 'Clio Williams', '', 1993, 'France', 'FR', 'Common', 150, 175, 7.8, 215, 990, 9400, 'A 2.0 litre homologation special named after Renault’s Formula 1 engine partnership.', array['street']::text[], array['everyday']::text[]),
  ('toyota-ae86', 'Toyota', 'Sprinter Trueno', 'AE86', 1983, 'Japan', 'JP', 'Common', 130, 149, 8.5, 200, 940, 13200, 'Rear-wheel drive, a revvy 4A-GE twin-cam and pop-up lights. Mountain-pass drifters made it famous.', array['street']::text[], array['everyday', 'jdm']::text[]),
  ('honda-civic-ek9', 'Honda', 'Civic Type R', 'EK9', 1997, 'Japan', 'JP', 'Common', 185, 160, 6.7, 225, 1050, 16000, 'A hand-ported 1.6 litre VTEC making 185 hp, seam-welded shell and a helical limited-slip differential.', array['street']::text[], array['everyday', 'jdm']::text[])
on conflict (id) do update set make = excluded.make, model = excluded.model, gen = excluded.gen, year = excluded.year, country = excluded.country, cc = excluded.cc, tier = excluded.tier, hp = excluded.hp, nm = excluded.nm, acc = excluded.acc, top = excluded.top, kg = excluded.kg, value = excluded.value, blurb = excluded.blurb, pools = excluded.pools, tastes = excluded.tastes;

insert into public.race_events (id, kind, len, place, fee, win, points) values
  ('sprint', 'Sprint', 800, 'Suzuka East straight', 500, 2500, 120),
  ('drag', 'Drag', 402, 'Quarter mile, Santa Pod', 300, 1500, 80),
  ('run', 'Highway run', 1600, 'Autobahn A9, closed section', 1000, 6000, 220)
on conflict (id) do update set kind = excluded.kind, len = excluded.len, place = excluded.place, fee = excluded.fee, win = excluded.win, points = excluded.points;

insert into public.seasons (id, ends_at) values (4, now() + interval '12 days 4 hours') on conflict (id) do nothing;

insert into public.calendar_events (starts_at, name, rule, prize, event_id, fee, featured) values
  (now() + interval '245031 seconds', 'Suzuka Sprint', '800 m · JDM cars only', 'Apex pack', 'sprint', 500, true),
  (now() + interval '331431 seconds', 'Monte Carlo Rally', '1,600 m · Rally class', '10,000 CR', 'run', 1000, false),
  (now() + interval '849831 seconds', 'Quarter Mile Night', '402 m · Any car', 'Rare car', 'drag', 300, false),
  (now() + interval '936231 seconds', 'Autobahn Run', '1,600 m · Supercars', 'Legendary pack', 'run', 1000, false),
  (now() + interval '1454631 seconds', 'Classics Cup', '800 m · Pre-1990', 'Heritage pack', 'sprint', 500, false);

-- House sellers keep the market stocked; one recent sale per car sets its 30-day average.
insert into public.listings (seller_name, car_id, level, price, ends_at) values
  ('k.watanabe', 'porsche-959', 2, 540000, now() + interval '8040 seconds'),
  ('lmarchetti', 'mercedes-300sl', 0, 475000, now() + interval '108000 seconds'),
  ('apex_hunter', 'ferrari-f40', 5, 455000, now() + interval '2280 seconds'),
  ('rallye.b', 'lancia-delta-evo', 3, 118000, now() + interval '18120 seconds'),
  ('bayside.r', 'nissan-skyline-r34', 4, 151000, now() + interval '42000 seconds'),
  ('2jz_only', 'toyota-supra-a80', 1, 79500, now() + interval '1320 seconds'),
  ('fairlady', 'datsun-240z', 2, 46000, now() + interval '259200 seconds'),
  ('dtm.88', 'bmw-m3-e30', 5, 83000, now() + interval '26100 seconds'),
  ('cossie', 'ford-sierra-cosworth', 0, 38500, now() + interval '93600 seconds'),
  ('touge.t', 'toyota-ae86', 3, 15800, now() + interval '17400 seconds'),
  ('f.giraud', 'renault-clio-williams', 1, 8900, now() + interval '172800 seconds'),
  ('monte64', 'mini-cooper-s', 0, 7200, now() + interval '3300 seconds');

insert into public.sales (car_id, price, sold_at) values
  ('porsche-959', 512000, now() - interval '10 days'),
  ('mercedes-300sl', 498000, now() - interval '10 days'),
  ('ferrari-f40', 420000, now() - interval '10 days'),
  ('lancia-delta-evo', 109000, now() - interval '10 days'),
  ('nissan-skyline-r34', 146000, now() - interval '10 days'),
  ('toyota-supra-a80', 86000, now() - interval '10 days'),
  ('datsun-240z', 44500, now() - interval '10 days'),
  ('bmw-m3-e30', 72000, now() - interval '10 days'),
  ('ford-sierra-cosworth', 41000, now() - interval '10 days'),
  ('toyota-ae86', 13200, now() - interval '10 days'),
  ('renault-clio-williams', 9400, now() - interval '10 days'),
  ('mini-cooper-s', 7600, now() - interval '10 days');
