// Generates supabase/catalog.sql (cars + race events, safe to re-run on a live database) and
// supabase/seed.sql (catalog plus demo listings and calendar, for `supabase db reset`) from the shared
// game data, so the database and the client never disagree on the catalog. Run with: npm run db:seed
import { writeFileSync } from 'node:fs'
import { CATALOG } from '../supabase/functions/_shared/game/catalog.ts'
import { RACE_EVENTS } from '../supabase/functions/_shared/game/race.ts'
import { seedEvents, seedListings } from '../src/api/seed.ts'

const NL = '\n'
const q = (v: string) => `'${v.replace(/'/g, "''")}'`
const nul = (v: string | undefined) => (v ? q(v) : 'null')
const arr = (v: string[]) => `array[${v.map(q).join(', ')}]::text[]`
const later = (ms: number) => `now() + interval '${Math.round(ms / 1000)} seconds'`

const catalog: string[] = ['-- Generated by scripts/gen-seed.ts. Do not edit by hand. Safe to run repeatedly.', '']

catalog.push('insert into public.cars (id, make, model, gen, year, country, cc, tier, hp, nm, acc, top, kg, value, blurb, pools, tastes, photo_url, photo_credit) values')
catalog.push(
  CATALOG.map(c =>
    `  (${[q(c.id), q(c.make), q(c.model), q(c.gen), c.year, q(c.country), q(c.cc), q(c.tier), c.hp, c.nm, c.acc, c.top, c.kg, c.value, q(c.blurb), arr(c.pools), arr(c.tastes), nul(c.photoUrl), nul(c.photoCredit)].join(', ')})`,
  ).join(',' + NL) +
    NL + 'on conflict (id) do update set make = excluded.make, model = excluded.model, gen = excluded.gen, year = excluded.year, country = excluded.country, cc = excluded.cc, tier = excluded.tier, hp = excluded.hp, nm = excluded.nm, acc = excluded.acc, top = excluded.top, kg = excluded.kg, value = excluded.value, blurb = excluded.blurb, pools = excluded.pools, tastes = excluded.tastes, photo_url = excluded.photo_url, photo_credit = excluded.photo_credit;',
  '',
)

catalog.push('insert into public.race_events (id, kind, len, place, fee, win, points) values')
catalog.push(
  RACE_EVENTS.map(e => `  (${[q(e.id), q(e.kind), e.len, q(e.place), e.fee, e.win, e.points].join(', ')})`).join(',' + NL) +
    NL + 'on conflict (id) do update set kind = excluded.kind, len = excluded.len, place = excluded.place, fee = excluded.fee, win = excluded.win, points = excluded.points;',
  '',
)

const now = Date.now()
const out: string[] = [...catalog]

out.push(`insert into public.seasons (id, ends_at) values (4, now() + interval '12 days 4 hours') on conflict (id) do nothing;`, '')

out.push('insert into public.calendar_events (starts_at, name, rule, prize, event_id, fee, featured) values')
out.push(seedEvents(now).map(e => `  (${[later(e.date - now), q(e.name), q(e.rule), q(e.prize), q(e.eventId), e.fee, e.featured].join(', ')})`).join(',' + NL) + ';', '')

const listings = seedListings(now)
out.push('-- House sellers keep the market stocked; one recent sale per car sets its 30-day average.')
out.push('insert into public.listings (seller_name, car_id, level, price, ends_at) values')
out.push(listings.map(l => `  (${[q(l.seller), q(l.carId), l.level, l.price, later(l.endsAt - now)].join(', ')})`).join(',' + NL) + ';', '')
out.push('insert into public.sales (car_id, price, sold_at) values')
out.push(listings.map(l => `  (${q(l.carId)}, ${l.avg}, now() - interval '10 days')`).join(',' + NL) + ';', '')

writeFileSync(new URL('../supabase/catalog.sql', import.meta.url), catalog.join(NL))
writeFileSync(new URL('../supabase/seed.sql', import.meta.url), out.join(NL))
console.log(`catalog.sql + seed.sql: ${CATALOG.length} cars, ${RACE_EVENTS.length} race events, ${listings.length} listings`)
